In [ ]:
import numpy as np

array_1 = np.arange(10)
print(array_1)

array_2 = np.arange(1,10)
print(array_2)

array_2 = np.arange(1,10, 2) # array com passo
print(array_2)

array_zeros = np.zeros(5) # 5 arrays com valor zero
print(array_zeros)

array_uns = np.ones(5) # 5 arrays com valor um
print(array_uns)

valores_espacado = np.linspace(5, 6, 7) #cria 7 numeros espaçados entre 5 e 6
print(valores_espacado)
#Excluir o último valor: Use endpoint=False para criar sequências que não incluem o valor final.

[0 1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]
[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]


TypeError: unsupported format string passed to numpy.ndarray.__format__