In [6]:
import numpy as np

matriz = np.array([[1,2,3], [4,5,6]])
print(matriz)
print('tamanho:', matriz.size)
print('formato:', matriz.shape)
print('dimensão:', matriz.ndim)
print('tipoo:', matriz.dtype)

matriz2 = np.array([[1],[2],[3], [4],[5],[6]])
print(matriz2)
print('tamanho:', matriz2.size)
print('formato:', matriz2.shape)
print('dimensão:', matriz2.ndim)
print('tipoo:', matriz2.dtype)


[[1 2 3]
 [4 5 6]]
tamanho: 6
formato: (2, 3)
dimensão: 2
tipoo: int64
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
tamanho: 6
formato: (6, 1)
dimensão: 2
tipoo: int64
