In [ ]:
import numpy as np

quantidades = np.array([[10, 5, 8], # Produto A
                        [3, 7, 2], # Produto B
                        [4, 6, 5]]) # Produto C

# Preços unitários de cada produto em cada filial
precos = np.array([[20, 18, 22],
                   [50, 45, 55],
                   [30, 35, 25]])

resultado = quantidades * precos
print(resultado)

resultado_produto = resultado.sum(axis=1 ) #eixo x ---
print(resultado_produto)

[[200  90 176]
 [150 315 110]
 [120 210 125]]
[466 575 455]
