In [ ]:
import numpy as np
#pode se faz sum, max, min
#levando em consideração os eixos (axis = 0 (vertical), axis = 1 (horizontal))
matriz = np.array([[8.5, 8.6, 7.7, 5.4],
                   [9.5, 8.0, 8.8, 6.0],
                   [10.0, 6.5, 4.2, 9.2]])

print(matriz)

matriz_media_vertical = np.mean(matriz, axis=0) #vertical
matriz_media_horizontal = np.mean(matriz, axis = 1) #horizontal
print(matriz_media_vertical)
print(matriz_media_horizontal)
posicao_menor_media = np.argmin(matriz_media_horizontal)
print('Indice_Minimo', posicao_menor_media)
max_matriz = np.max(matriz, axis = 1)
print(max_matriz)
max_matriz = np.max(matriz, axis = 0)

# A função numpy.argmin(a, axis=None)
# retorna os índices dos valores mínimos 
# ao longo de um eixo específico em um array. 
#O ARGMAX retorna o maior valor
a = np.array([5, 2, 8, 1, 3])
indice = np.argmin(a) # Retorna 3, pois 1 está na posição 3 (índice base 0)
print(indice) 







[[ 8.5  8.6  7.7  5.4]
 [ 9.5  8.   8.8  6. ]
 [10.   6.5  4.2  9.2]]
[9.33333333 7.7        6.9        6.86666667]
[7.55  8.075 7.475]
Indice_Minimo 2
[ 8.6  9.5 10. ]
