In [3]:
import numpy as np

valores = np.array([5, 10, 15, 25])
print(np.sqrt(valores))
print(np.exp(valores))
print(np.log(valores +1 ))
print(np.sin(valores))
print(np.cos(valores))


[2.23606798 3.16227766 3.87298335 5.        ]
[1.48413159e+02 2.20264658e+04 3.26901737e+06 7.20048993e+10]
[1.79175947 2.39789527 2.77258872 3.25809654]
[-0.95892427 -0.54402111  0.65028784 -0.13235175]
[ 0.28366219 -0.83907153 -0.75968791  0.99120281]
