In [2]:
import numpy as np

array = np.array([50, 80, 100, 120, 150])
print(array)
print('Caracteristica do ARRAY')
print('TAMANHO:', array.size)
print('FORMATO:', array.shape)
print('DIMENSÃO:', array.ndim)
print('TIPO:',array.dtype)

matriz = np.array([[10, 20, 30], [40, 50, 60]])
print('*' * 50)
print(matriz)
print('Caracteristica do MATRIZ')
print('TAMANHO:', matriz.size)
print('FORMATO:', matriz.shape)
print('DIMENSÃO:', matriz.ndim)
print('TIPO:',matriz.dtype)



[ 50  80 100 120 150]
Caracteristica do ARRAY
TAMANHO: 5
FORMATO: (5,)
DIMENSÃO: 1
TIPO: int64
**************************************************
[[10 20 30]
 [40 50 60]]
Caracteristica do MATRIZ
TAMANHO: 6
FORMATO: (2, 3)
DIMENSÃO: 2
TIPO: int64
